-- Tablas Staging para PostgreSQL
-- Esquemas: sire_sta, raw

-- Tabla raw para BDUA
CREATE TABLE IF NOT EXISTS sire_sta.raw_bdua (
    id                             BIGSERIAL PRIMARY KEY,
    tipo_identificacion            VARCHAR(50),
    numero_identificacion          BIGINT,
    primer_apellido                VARCHAR(100),
    segundo_apellido               VARCHAR(100),
    primer_nombre                  VARCHAR(100),
    segundo_nombre                 VARCHAR(100),
    fecha_nacimiento               DATE,
    sexo                           VARCHAR(10),
    cod_departamento               INTEGER,
    cod_municipio                  INTEGER,
    zona                           VARCHAR(50),
    cod_entidad                    VARCHAR(50),
    nombre_entidad                 VARCHAR(100),
    fecha_afiliacion               DATE,
    estado_afiliacion              VARCHAR(50),
    tipo_documento_cotizante       VARCHAR(50),
    numero_documento_cotizante     BIGINT,
    tipo_cotizante                 VARCHAR(50),
    tipo_afiliado                  VARCHAR(50),
    parentesco                     VARCHAR(70),
    discapacidad                   VARCHAR(50),
    tipo_poblacion_especial        VARCHAR(100),
    etnia                          VARCHAR(100),
    nombre_resguardo               VARCHAR(100),
    ips_primaria                   VARCHAR(100),
    tipo_identificacion_aportante  VARCHAR(50),
    numero_identificacion_aportante INTEGER,
    razon_social_aportante         VARCHAR(250),
    actividad_economica            INTEGER,
    regimen                        VARCHAR(30),
    load_date                      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    file_name                      VARCHAR(255),
    id_estadistico_persona         VARCHAR(300),
    llave_direccion                VARCHAR(250),
    persona_hash                   VARCHAR(40)
);

-- Tabla raw para RUES
CREATE TABLE IF NOT EXISTS sire_sta.raw_rues (
    id_estadistico_empresa                   VARCHAR(300),
    llave_direccion                          VARCHAR(250),
    codigo_camara                            VARCHAR(50),
    camara_comercio                          VARCHAR(100),
    matricula                                VARCHAR(50),
    inscripcion_proponente                   VARCHAR(50),
    razon_social                             VARCHAR(250),
    primer_apellido                          VARCHAR(100),
    segundo_apellido                         VARCHAR(100),
    primer_nombre                            VARCHAR(100),
    segundo_nombre                           VARCHAR(100),
    sigla                                    VARCHAR(50),
    codigo_clase_identificacion              VARCHAR(50),
    clase_identificacion                     VARCHAR(100),
    numero_identificacion                    VARCHAR(50),
    nit                                      VARCHAR(50),
    digito_verificacion                      VARCHAR(10),
    cod_ciiu_act_econ_pri                    VARCHAR(10),
    cod_ciiu_act_econ_sec                    VARCHAR(10),
    ciiu3                                    VARCHAR(10),
    ciiu4                                    VARCHAR(10),
    fecha_matricula                          DATE,
    fecha_renovacion                         DATE,
    ultimo_ano_renovado                      INTEGER,
    fecha_vigencia                           DATE,
    fecha_cancelacion                        DATE,
    codigo_tipo_sociedad                     VARCHAR(50),
    tipo_sociedad                            VARCHAR(100),
    codigo_organizacion_juridica             VARCHAR(50),
    organizacion_juridica                    VARCHAR(100),
    codigo_categoria_matricula               VARCHAR(50),
    categoria_matricula                      VARCHAR(100),
    codigo_estado_matricula                  VARCHAR(50),
    estado_matricula                         VARCHAR(100),
    clase_identificacion_rl                  VARCHAR(50),
    num_identificacion_representante_legal   VARCHAR(50),
    representante_legal                      VARCHAR(200),
    fecha_actualizacion                      TIMESTAMP,
    md5_hash                                 VARCHAR(40),
    load_date                                TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
