-- Tabla de control para IDs estadísticos generados
-- Esquema: SIRE_STA

ALTER SESSION SET CURRENT_SCHEMA = SIRE_STA;

-- Tabla de control de IDs generados
CREATE TABLE control_ids_generados (
    id                        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estadistico            VARCHAR2(100) UNIQUE,
    tipo_entidad              VARCHAR2(2) CHECK (tipo_entidad IN ('01', '02')),
    tipo_documento            VARCHAR2(50),
    numero_documento          VARCHAR2(50),
    fecha_generacion          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    estado                    VARCHAR2(20) DEFAULT 'generado' CHECK (estado IN ('generado', 'utilizado', 'error')),
    observaciones             CLOB,
    load_datetime             TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Índices para optimizar consultas
CREATE INDEX idx_control_ids_tipo_entidad ON control_ids_generados(tipo_entidad);
CREATE INDEX idx_control_ids_documento ON control_ids_generados(tipo_documento, numero_documento);
CREATE INDEX idx_control_ids_fecha ON control_ids_generados(fecha_generacion);
CREATE INDEX idx_control_ids_estado ON control_ids_generados(estado);

-- Comentarios
COMMENT ON TABLE control_ids_generados IS 'Tabla de control para IDs estadísticos generados por la API';
COMMENT ON COLUMN control_ids_generados.id_estadistico IS 'ID estadístico generado (01+consecutivo para personas, 02+consecutivo para empresas)';
COMMENT ON COLUMN control_ids_generados.tipo_entidad IS 'Tipo de entidad: 01=Persona, 02=Empresa';
COMMENT ON COLUMN control_ids_generados.estado IS 'Estado del ID: generado, utilizado, error';

COMMIT;
