-- Crear esquemas para Oracle
-- Este script se ejecuta al inicializar el contenedor Oracle

-- Crear usuario SIRE_DV (Data Vault)
CREATE USER SIRE_DV IDENTIFIED BY sire_password;
GRANT CONNECT, RESOURCE TO SIRE_DV;
GRANT CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO SIRE_DV;
GRANT UNLIMITED TABLESPACE TO SIRE_DV;

-- Crear usuario SIRE_STA (Staging)
CREATE USER SIRE_STA IDENTIFIED BY sire_password;
GRANT CONNECT, RESOURCE TO SIRE_STA;
GRANT CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO SIRE_STA;
GRANT UNLIMITED TABLESPACE TO SIRE_STA;

-- Otorgar permisos entre esquemas
GRANT SELECT, INSERT, UPDATE, DELETE ON SIRE_DV.* TO SIRE_STA;
GRANT SELECT, INSERT, UPDATE, DELETE ON SIRE_STA.* TO SIRE_DV;

COMMIT;
