CREATE USER SIRE_DV IDENTIFIED BY sire_password;
GRANT CONNECT, RESOURCE TO SIRE_DV;
ALTER USER SIRE_DV DEFAULT TABLESPACE users;
ALTER USER SIRE_DV TEMPORARY TABLESPACE temp;
ALTER USER SIRE_DV QUOTA UNLIMITED ON users;

CREATE USER SIRE_STG IDENTIFIED BY sire_password;
GRANT CONNECT, RESOURCE TO SIRE_STG;
ALTER USER SIRE_STG DEFAULT TABLESPACE users;
ALTER USER SIRE_STG TEMPORARY TABLESPACE temp;
ALTER USER SIRE_STG QUOTA UNLIMITED ON users; 