-- Crear usuario SIRE_STG si no existe
CREATE USER SIRE_STG IDENTIFIED BY sire_password;
GRANT CONNECT, RESOURCE TO SIRE_STG;
ALTER USER SIRE_STG DEFAULT TABLESPACE users;
ALTER USER SIRE_STG TEMPORARY TABLESPACE temp;
ALTER USER SIRE_STG QUOTA UNLIMITED ON users;

-- Crear usuario SIRE_DV si no existe
CREATE USER SIRE_DV IDENTIFIED BY sire_password;
GRANT CONNECT, RESOURCE TO SIRE_DV;
ALTER USER SIRE_DV DEFAULT TABLESPACE users;
ALTER USER SIRE_DV TEMPORARY TABLESPACE temp;
ALTER USER SIRE_DV QUOTA UNLIMITED ON users;

-- Crear usuario sire_user para conexiones desde aplicaciones
CREATE USER sire_user IDENTIFIED BY sire_pass;
GRANT CONNECT, RESOURCE TO sire_user;
ALTER USER sire_user DEFAULT TABLESPACE users;
ALTER USER sire_user TEMPORARY TABLESPACE temp;
ALTER USER sire_user QUOTA UNLIMITED ON users;

-- Otorgar permisos entre esquemas
GRANT SELECT, INSERT, UPDATE, DELETE ON SIRE_STG.* TO sire_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON SIRE_DV.* TO sire_user;

-- Crear tabla de prueba en SIRE_STG
CREATE TABLE SIRE_STG.raw_obt_personas (
    id                        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estadistico            VARCHAR2(100),
    tipo_documento            VARCHAR2(50),
    numero_documento          VARCHAR2(50),
    primer_nombre             VARCHAR2(100),
    segundo_nombre            VARCHAR2(100),
    primer_apellido           VARCHAR2(100),
    segundo_apellido          VARCHAR2(100),
    fecha_nacimiento          DATE,
    sexo_an                   VARCHAR2(50),
    codigo_municipio_nacimiento      VARCHAR2(50), --divipola
    codigo_pais_nacimiento           varchar2(3), --m49
    fecha_defuncion           DATE,
    load_datetime             TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    id_log_etl                NUMBER
);

-- Crear tabla de prueba en SIRE_DV
CREATE TABLE SIRE_DV.catalogo_tipo_documento (
    id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_documento          VARCHAR2(4), 
    descripcion             VARCHAR2(250),
    codigo_tipo_unidad      VARCHAR2(3),
    fecha_creacion          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_carga           VARCHAR2(50),
    estado                  VARCHAR2(20) DEFAULT 'ACTIVO'
);

-- Insertar datos de prueba
INSERT INTO SIRE_DV.catalogo_tipo_documento (tipo_documento, descripcion, codigo_tipo_unidad) 
VALUES ('CC', 'Cédula de Ciudadanía', 'PER');

INSERT INTO SIRE_DV.catalogo_tipo_documento (tipo_documento, descripcion, codigo_tipo_unidad) 
VALUES ('CE', 'Cédula de Extranjería', 'PER');

INSERT INTO SIRE_DV.catalogo_tipo_documento (tipo_documento, descripcion, codigo_tipo_unidad) 
VALUES ('NIT', 'Número de Identificación Tributaria', 'EMP');

COMMIT; 