-- Tablas Data Vault para Oracle
-- Esquema: SIRE_DV

ALTER SESSION SET CURRENT_SCHEMA = SIRE_DV;

-- Tabla de log ETL
CREATE TABLE log_etl (
    id                        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_uuid                  VARCHAR2(100) UNIQUE,
    start_time                TIMESTAMP,
    end_time                  TIMESTAMP,
    estado                    VARCHAR2(20) CHECK (estado IN ('SUCCESS', 'FAILURE')),
    registros_cargados        NUMBER,
    tabla_destino             VARCHAR2(255),
    mensaje_error             CLOB,
    nombre_etl                VARCHAR2(255),
    descripcion_etl           VARCHAR2(255),
    tiempo_ejecucion_segundos NUMBER,
    nombre_archivo            VARCHAR2(255),
    hash_archivo              VARCHAR2(255) UNIQUE
);

-- Catálogo de fuentes de registro
CREATE TABLE catalogo_fuente_registro (
    id                      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_fuente               VARCHAR2(4),
    nombre_fuente           VARCHAR2(15),
    periodicidad_fuente     VARCHAR2(20) CHECK (periodicidad_fuente IN ('Mensual', 'Anual', 'Trimestral', 'Semanal', 'Diario', 'Otro')),
    vigencia_fuente         VARCHAR2(20),
    descripcion             VARCHAR2(250),
    sistema_origen          VARCHAR2(100),
    tipo_fuente             VARCHAR2(50),
    fecha_creacion          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_carga           VARCHAR2(50),
    estado                  VARCHAR2(20) DEFAULT 'ACTIVO'
);

-- Hub Persona
CREATE TABLE hub_persona (
    id                     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estadistico         VARCHAR2(300) UNIQUE,
    load_datetime          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_fuente_registro     NUMBER REFERENCES catalogo_fuente_registro(id),
    id_log_etl             NUMBER REFERENCES log_etl(id),
    md5_hash               VARCHAR2(40) UNIQUE
);

-- Satélite Persona (PSEUDONIMIZADO - Sin campos sensibles de OBT)
CREATE TABLE sat_persona (
    id                        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estadistico            VARCHAR2(300) REFERENCES hub_persona(id_estadistico),
    fecha_nacimiento          DATE,
    sexo                      VARCHAR2(50),
    codigo_municipio_nacimiento VARCHAR2(5),
    codigo_pais_nacimiento    VARCHAR2(3),
    fecha_defuncion           DATE,
    estado_civil              VARCHAR2(50),
    etnia                     VARCHAR2(90),
    discapacidad              VARCHAR2(50),
    tipo_poblacion_especial   VARCHAR2(100),
    nombre_resguardo          VARCHAR2(100),
    md5_hash                  VARCHAR2(40) UNIQUE,
    load_datetime             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_fuente_registro        NUMBER REFERENCES catalogo_fuente_registro(id),
    id_log_etl                NUMBER REFERENCES log_etl(id)
);

-- Hub Empresa
CREATE TABLE hub_empresa (
    id                     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estadistico         NUMBER UNIQUE,
    load_datetime          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_fuente_registro     NUMBER REFERENCES catalogo_fuente_registro(id),
    id_log_etl             NUMBER REFERENCES log_etl(id),
    md5_hash               VARCHAR2(40) UNIQUE
);

-- Satélite Empresa (PSEUDONIMIZADO - Sin campos sensibles de OBT)
CREATE TABLE sat_empresa (
    id                                     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estadistico_empresa                 NUMBER REFERENCES hub_empresa(id_estadistico),
    codigo_camara                          VARCHAR2(250),
    camara_comercio                        VARCHAR2(250),
    matricula                              VARCHAR2(250),
    inscripcion_proponente                 VARCHAR2(250),
    sigla                                  VARCHAR2(250),
    fecha_matricula                        DATE,
    fecha_renovacion                       DATE,
    ultimo_anio_renovado                   NUMBER,
    fecha_vigencia                         DATE,
    fecha_cancelacion                      DATE,
    codigo_tipo_sociedad                   VARCHAR2(250),
    tipo_sociedad                          VARCHAR2(250),
    codigo_organizacion_juridica           VARCHAR2(250),
    organizacion_juridica                  VARCHAR2(250),
    codigo_categoria_matricula             VARCHAR2(250),
    categoria_matricula                    VARCHAR2(250),
    codigo_estado_matricula                VARCHAR2(250),
    estado_matricula                       VARCHAR2(250),
    fecha_actualizacion                    TIMESTAMP,
    codigo_clase_identificacion            VARCHAR2(250),
    digito_verificacion                    VARCHAR2(250),
    estatus                                VARCHAR2(50),
    load_datetime                          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_fuente_registro                     NUMBER REFERENCES catalogo_fuente_registro(id),
    id_log_etl                             NUMBER REFERENCES log_etl(id),
    md5_hash                               VARCHAR2(40) UNIQUE
);

-- Tabla de afiliaciones (Link)
CREATE TABLE link_afiliacion (
    id                             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_hub_persona_afiliada        NUMBER REFERENCES hub_persona(id_estadistico),
    id_hub_persona_cotizante       NUMBER REFERENCES hub_persona(id_estadistico),
    id_hub_aportante_emp           NUMBER REFERENCES hub_empresa(id_estadistico),
    id_cod_departamento            NUMBER,
    id_cod_municipio               NUMBER,
    id_zona                        NUMBER,
    tipo_cotizante                 VARCHAR2(50),
    tipo_afiliado                  VARCHAR2(50),
    parentesco                     VARCHAR2(70),
    ips_primaria                   VARCHAR2(100),
    fecha_afiliacion               DATE,
    regimen                        VARCHAR2(30),
    estado_afiliacion              VARCHAR2(30),
    load_datetime                  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_fuente_registro             NUMBER REFERENCES catalogo_fuente_registro(id),
    id_log_etl                     NUMBER REFERENCES log_etl(id),
    md5_hash                       VARCHAR2(40) UNIQUE
);

COMMIT;
