-- Tablas OBT para Oracle (equivalente a PostgreSQL)
-- Esquema: SIRE_STA

ALTER SESSION SET CURRENT_SCHEMA = SIRE_STA;

-- Tabla OBT Personas (ID estadístico 01+Consecutivo)
CREATE TABLE raw_obt_personas (
    id                        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estadistico            VARCHAR2(100),
    tipo_documento            VARCHAR2(50),
    numero_documento          VARCHAR2(50),
    primer_nombre             VARCHAR2(100),
    segundo_nombre            VARCHAR2(100),
    primer_apellido           VARCHAR2(100),
    segundo_apellido          VARCHAR2(100),
    fecha_nacimiento          DATE,
    sexo_an                   VARCHAR2(50),
    codigo_municipio_nacimiento VARCHAR2(50), -- divipola
    codigo_pais_nacimiento    VARCHAR2(3), -- m49
    fecha_defuncion           DATE,
    load_datetime             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_log_etl                NUMBER
);

-- Tabla OBT Empresas (ID estadístico 02+Consecutivo)
-- ID estadístico 01+Consecutivo solo cuando empresa tiene tipo documento CC
CREATE TABLE raw_obt_empresas (
    id                        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estadistico            VARCHAR2(100),
    razon_social              VARCHAR2(250),
    tipo_documento            VARCHAR2(50),
    numero_documento          VARCHAR2(50),
    digito_verificacion       VARCHAR2(10),
    codigo_camara             VARCHAR2(50),
    camara_comercio           VARCHAR2(100),
    matricula                 VARCHAR2(50),
    fecha_matricula           DATE,
    fecha_renovacion          DATE,
    ultimo_ano_renovado       NUMBER,
    fecha_vigencia            DATE,
    fecha_cancelacion         DATE,
    codigo_tipo_sociedad      VARCHAR2(50),
    tipo_sociedad             VARCHAR2(100),
    codigo_organizacion_juridica VARCHAR2(50),
    organizacion_juridica     VARCHAR2(100),
    codigo_estado_matricula   VARCHAR2(50),
    estado_matricula          VARCHAR2(100),
    representante_legal       VARCHAR2(200),
    num_identificacion_representante_legal VARCHAR2(50),
    clase_identificacion_rl   VARCHAR2(50),
    fecha_actualizacion       TIMESTAMP,
    load_datetime             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_log_etl                NUMBER
);

-- Índices para optimizar consultas
CREATE INDEX idx_obt_personas_id_estadistico ON raw_obt_personas(id_estadistico);
CREATE INDEX idx_obt_personas_documento ON raw_obt_personas(tipo_documento, numero_documento);
CREATE INDEX idx_obt_empresas_id_estadistico ON raw_obt_empresas(id_estadistico);
CREATE INDEX idx_obt_empresas_documento ON raw_obt_empresas(tipo_documento, numero_documento);

-- Comentarios
COMMENT ON TABLE raw_obt_personas IS 'Tabla OBT para personas con IDs estadísticos';
COMMENT ON TABLE raw_obt_empresas IS 'Tabla OBT para empresas con IDs estadísticos';

COMMIT;
